import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import NavigationHeader from "@/components/common/navigation/NavigationHeader";
import { ThemeProvider } from "@/components/theme-provider"

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
});

export const metadata: Metadata = {
  title: "MOO BOX",
  description: "Generated by create next app",
  icons: {
    icon: "/images/mooboxBlack.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={pretendard.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <NavigationHeader/>
        {children}
      </ThemeProvider>
      </body>
    </html>
  );
}
